services:
  immichframe:
    build:
      context: ..
      target: final
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      # - PATH/TO/CONFIG:/app/Config
      - ../data:/data